In [15]:
import pandas as pd
import numpy as np
import datetime
import json

In [2]:
df = pd.read_csv('CSV/all_csv.csv')

In [3]:
df

,UC2_Literal,Report Number,Report Date,Location,Beat,Neigborhood,NPU,Lat,Long
0,ROBBERY-PEDESTRIAN,190312274,1/31/2019,800 HUTCHENS RD,313.0,South River Gardens,Z,33.67102,-84.36187
1,ROBBERY-COMMERCIAL,190311297,1/31/2019,2690 CAMPBELLTON RD SW,410.0,Campbellton Road,R,33.70208,-84.47641
2,ROBBERY-PEDESTRIAN,190312026,1/31/2019,710 PEACHTREE ST NE @HOWELL HOUSE,505.0,Midtown,E,33.77407,-84.38526
3,ROBBERY-RESIDENCE,190310320,1/31/2019,653 BOULEVARD,603.0,Old Fourth Ward,M,33.77244,-84.37129
4,AGG ASSAULT,190310550,1/31/2019,1994 BENT CREEK WAY SW,410.0,Campbellton Road,R,33.70050,-84.46574
...,...,...,...,...,...,...,...,...,...
25088,BURGLARY-RESIDENCE,192441604,9/1/2019,392 BELGARDE PL SE,312.0,Orchard Knob,Z,33.66480,-84.37716
25089,BURGLARY-RESIDENCE,192442165,9/1/2019,2400 CAMPBELLTON RD SW,410.0,Campbellton Road,R,33.70382,-84.46637
25090,BURGLARY-RESIDENCE,192440400,9/1/2019,2342 MACON DR SW,310.0,Swallow Circle/Baywood,Z,33.69049,-84.39064
25091,AGG ASSAULT,192442584,9/1/2019,PIEDMONT RD NE / BUFORD HIGHWAY CONN NE,211.0,NaN,F,33.81409,-84.36662
25092,AGG ASSAULT,192441562,9/1/2019,717 LEE ST SW,401.0,West End,T,33.73516,-84.41421

In [4]:
dropped = df[['Lat', 'Long', 'UC2_Literal', 'Report Date']]

In [5]:
dropped

            Lat      Long         UC2_Literal Report Date
0      33.67102 -84.36187  ROBBERY-PEDESTRIAN   1/31/2019
1      33.70208 -84.47641  ROBBERY-COMMERCIAL   1/31/2019
2      33.77407 -84.38526  ROBBERY-PEDESTRIAN   1/31/2019
3      33.77244 -84.37129   ROBBERY-RESIDENCE   1/31/2019
4      33.70050 -84.46574         AGG ASSAULT   1/31/2019
...         ...       ...                 ...         ...
25088  33.66480 -84.37716  BURGLARY-RESIDENCE    9/1/2019
25089  33.70382 -84.46637  BURGLARY-RESIDENCE    9/1/2019
25090  33.69049 -84.39064  BURGLARY-RESIDENCE    9/1/2019
25091  33.81409 -84.36662         AGG ASSAULT    9/1/2019
25092  33.73516 -84.41421         AGG ASSAULT    9/1/2019

[25093 rows x 4 columns]

In [12]:
data = []
for row in dropped.itertuples(index = False):
    data.append({
        'COORDINATES': [row[0], row[1]],
        'TYPE': row[2],
        'DATE': datetime.datetime.strptime(row[3], '%m/%d/%Y').strftime("%Y-%m-%d %H:%M:%S")
    })

In [17]:
with open('2019_data.json', 'w') as f:
    json.dump(data, f)